101 EJERCICIOS DE NUMPY

In [1]:
import numpy as np

In [3]:
print(np.__version__)

1.25.2


Unidimensional array

In [6]:
x= np.arange(10)
x
type(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]


Boolean array

In [7]:
y= np.full((3,3),True, dtype= bool)
print(y)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [8]:
z= np.ones((3,3), dtype=bool)
print(z)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Introducing all the arguments np.arange has....

np.arange(start, stop, step)

In [35]:
a= np.arange(0,10,2) #step is used for 'jumping' from one item to the other n steps ahead or backwards.

In [36]:
print(a)

[0 2 4 6 8]


Extracting items after a given condition

In [9]:
a= np.arange(10)

In [10]:
a[a%2==1]

array([1, 3, 5, 7, 9])

In [11]:
a[a<5]

array([0, 1, 2, 3, 4])

Replacing items through a given condition

In [12]:
a= np.arange(10)

replace all odd numbers with a -1

In [14]:
a[a%2==1]=-1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Create a new array from another after a given condition.

In [15]:
a=np.arange(10)

new array replacing all odd numbers with -1

In [16]:
b= np.where(a % 2 == 1, -1, a)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Reshaping arrays

In [17]:
a= np.arange(10)

In [18]:
a.reshape(2,-1) # the defaulted -1 sets the columns to align automatically

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
b= np.arange(12)

In [20]:
b.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
b.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

Stacking arrays

In [27]:
a= np.arange(10)
b= np.repeat(1,10)
print(a)
print(b)


[0 1 2 3 4 5 6 7 8 9]
[1 1 1 1 1 1 1 1 1 1]


In [29]:
a= np.arange(10).reshape(2,-1)
b= np.repeat(1,10).reshape(2,-1)
print('a =', a)
print('b =', b)



a = [[0 1 2 3 4]
 [5 6 7 8 9]]
b = [[1 1 1 1 1]
 [1 1 1 1 1]]


Now, the stacking...

In [30]:
np.concatenate([a,b], axis=0) # axis determines how we will concatenate or stack our two arrays. 0 means vertically, 1 means horizontally.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
np.concatenate([a,b], 1) # now we have stacked them horizontally, so there are more columns.

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Stacking using vstack (vertically) or hstack (horizontally)

In [33]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

np.array()

In [37]:
a= np.array([1,2,3]) #array converts a given iterable into an array
print(a)

[1 2 3]


In [38]:
b= [4,5,6]
c= np.array(b)
print(c)

[4 5 6]


In [40]:
type(b)

list

In [39]:
type(c)

numpy.ndarray

More features for manipulating and creating arrays from others arrays

In [41]:
a= np.array([1,2,3])

In [44]:
b= np.r_[np.repeat(a,3), np.tile(a,3)]  # np.r_ is an indexer that allows to concatenate items in the first axis (r >> rows)
print(b)                                # np.repeat is a Numpy built-in function that repeats each item of an array n number of times
                                        # np.tile is another Numpy function that tiles or repeat all the items of an array n number of times.                               

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [46]:
c= np.c_[np.repeat(a,3), np.tile(a,3)] # On the other hand, np.c_ is another indexer that concatenates the items in the second axis (c >> columns)
print(c)

[[1 1]
 [1 2]
 [1 3]
 [2 1]
 [2 2]
 [2 3]
 [3 1]
 [3 2]
 [3 3]]


Showcasing common items between 2 different arrays

In [49]:
a= np.arange(0,20,2)
b= np.arange(1,30,3)
print(a)
print(b)

[ 0  2  4  6  8 10 12 14 16 18]
[ 1  4  7 10 13 16 19 22 25 28]


In [51]:
c= np.intersect1d(a,b)  # np.intersect1d will fetch the elements that 2 arrays share in common. 
print(c)                # 1d stand for unidimensional array (this is how the result will be stored)

[ 4 10 16]


Comparing the items from 2 arrays and extracting the unique ones

In [3]:
a= np.array([1,2,3,4,5])
b= np.array([5,6,7,8,9])
np.setdiff1d(a,b)           # np.setdiff1d will compute the 'set difference' between two arrays.
                            # this means that the function will check for the items in both arrays, and return only those that are unique
                            # in the first array we input as argument in the function, in this case the unique element of a.

array([1, 2, 3, 4])

In [4]:
np.setdiff1d(b,a)          # Now, we showcase the unique elements in b.

array([6, 7, 8, 9])

Getting the indexes where two elements from two arrays match  (np.where function)

In [7]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)  # if an item in 'a' shares the same value and position as in one in 'b', 
                # a new array will be displayed with the index numbers from those matching items

(array([1, 3, 5, 7]),)

Extracting numbers between a given range from an array.

In [5]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a)

[ 2  6  1  9 10  3 27]


In [8]:
indexes= np.where(a >= 9) # np.where is Numpy function that finds the indexes of items after if given condition is fulfilled
a[indexes]  # We use indexing brackets to access the elements at those positions.

array([ 9, 10, 27])

Comparing two arrays, and outputting the maxximum value element-wise

First, the hard way...

In [10]:
def max(a,b): # Defining the max function which takes two scalars and returns the one with the higher value.
    if a>b:
        return a
    else:
        return b    

In [9]:
a= np.arange(1,10)
a.shape


(9,)

In [17]:
b= np.reshape(a,[3,3])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
c= np.reshape([1,2,3,4,5,6],[2,3])

In [15]:
print(c)

[[1 2 3]
 [4 5 6]]


In [26]:
d= np.arange(1,22)
d= d.reshape(3,7)
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
