101 EJERCICIOS DE NUMPY

In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.25.2


Unidimensional array

In [6]:
x= np.arange(10)
x
type(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]


Boolean array

In [7]:
y= np.full((3,3),True, dtype= bool)
print(y)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [8]:
z= np.ones((3,3), dtype=bool)
print(z)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Extracting items after a given condition

In [9]:
a= np.arange(10)

In [10]:
a[a%2==1]

array([1, 3, 5, 7, 9])

In [11]:
a[a<5]

array([0, 1, 2, 3, 4])

Replacing items through a given condition

In [12]:
a= np.arange(10)

replace all odd numbers with a -1

In [14]:
a[a%2==1]=-1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Create a new array from another after a given condition.

In [15]:
a=np.arange(10)

new array replacing all odd numbers with -1

In [16]:
b= np.where(a % 2 == 1, -1, a)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Reshaping arrays

In [17]:
a= np.arange(10)

In [18]:
a.reshape(2,-1) # the defaulted -1 sets the columns to align automatically

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
b= np.arange(12)

In [20]:
b.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
b.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

Stacking arrays

In [27]:
a= np.arange(10)
b= np.repeat(1,10)
print(a)
print(b)


[0 1 2 3 4 5 6 7 8 9]
[1 1 1 1 1 1 1 1 1 1]


In [29]:
a= np.arange(10).reshape(2,-1)
b= np.repeat(1,10).reshape(2,-1)
print('a =', a)
print('b =', b)



a = [[0 1 2 3 4]
 [5 6 7 8 9]]
b = [[1 1 1 1 1]
 [1 1 1 1 1]]


Now, the stacking...

In [30]:
np.concatenate([a,b], axis=0) # axis determines how we will concatenate or stack our two arrays. 0 means vertically, 1 means horizontally.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
np.concatenate([a,b], 1) # nos we have stacked them horizontally, so there are more columns.

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Stacking using vstack (vertically) or hstack (horizontally)

In [33]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [9]:
a= np.arange(1,10)
a.shape


(9,)

In [17]:
b= np.reshape(a,[3,3])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
c= np.reshape([1,2,3,4,5,6],[2,3])

In [15]:
print(c)

[[1 2 3]
 [4 5 6]]


In [26]:
d= np.arange(1,22)
d= d.reshape(3,7)
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
