# Práctica Clase 3

## Numpy

In [1]:
import numpy as np

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

A partir de una lista podemos crear un arreglo de numpy

In [2]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [3]:
arreglo = np.arange(8)
print(arreglo)

[0 1 2 3 4 5 6 7]


Algunas cosas que se pueden hacer con arreglos pero no con las listas:

1. Sumarle un mismo elemento

In [5]:
lista + 1

TypeError: can only concatenate list (not "int") to list

In [6]:
arreglo = arreglo + 1

In [7]:
arreglo

array([1, 2, 3, 4, 5, 6, 7, 8])

2. Elevar al cuadrado todos los elementos

In [8]:
lista**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [9]:
arreglo**2

array([ 1,  4,  9, 16, 25, 36, 49, 64], dtype=int32)

3. Sumar todos los elementos

In [10]:
print(arreglo.sum())
print(lista.sum())

36


AttributeError: 'list' object has no attribute 'sum'

In [11]:
n = 0
for e in lista:
    n = n + e
print(n)

15


In [12]:
arreglo.shape

(6,)

In [28]:
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (3, 6) 



In [30]:
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]] . Shape = (1, 6) 



In [31]:
arreglo = np.array([[1,2,3,4,5,6]]).T #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [25]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?

print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea

print('Arreglo de (2,n)')
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

print('Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto


Arreglo de (n,)
[1 2 3 4 5 6] . Shape = (6,) 

Arreglo de (2,n)
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (2, 6) 

Arreglo de (n,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1)


In [ ]:
### EXTRA 1###
#Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = np.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

In [43]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a1.shape

(2, 4)

In [44]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2.shape

(2, 4)

In [45]:
a3 = a1 * a2
a3.shape

(2, 4)

In [46]:
a3

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [2]:
import numpy as np

In [5]:
arr1 = np.arange(start=0,stop=10,step=1, dtype=int)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
arr2 = np.linspace(start=0,stop=9,num=100)
print(arr2)
print(len(arr2))

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.
 1.09090909 1.18181818 1.27272727 1.36363636 1.45454545 1.54545455
 1.63636364 1.72727273 1.81818182 1.90909091 2.         2.09090909
 2.18181818 2.27272727 2.36363636 2.45454545 2.54545455 2.63636364
 2.72727273 2.81818182 2.90909091 3.         3.09090909 3.18181818
 3.27272727 3.36363636 3.45454545 3.54545455 3.63636364 3.72727273
 3.81818182 3.90909091 4.         4.09090909 4.18181818 4.27272727
 4.36363636 4.45454545 4.54545455 4.63636364 4.72727273 4.81818182
 4.90909091 5.         5.09090909 5.18181818 5.27272727 5.36363636
 5.45454545 5.54545455 5.63636364 5.72727273 5.81818182 5.90909091
 6.         6.09090909 6.18181818 6.27272727 6.36363636 6.45454545
 6.54545455 6.63636364 6.72727273 6.81818182 6.90909091 7.
 7.09090909 7.18181818 7.27272727 7.36363636 7.45454545 7.54545455
 7.63636364 7.72727273 7.81818182 7.90909091 8.         8.09090909
 8.18181818

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [8]:
arr3 = np.arange(10,101)
print(arr3)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


In [12]:
9 % 3 # -> Resto == 0; significa que el numero es divisible por el otro numero

0

In [21]:
mask = ((arr3 % 3) == 0)
print(mask)

[False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False False  True False False  True
 False False  True False False  True False]


In [18]:
mask = []
for esasdasbiouda in arr3:
    if esasdasbiouda % 3 == 0:
        mask.append(esasdasbiouda)
    else:
        mask.append(False)
mask = np.array(mask)

In [22]:
mask

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False])

In [23]:
print(arr3[mask])

[12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81
 84 87 90 93 96 99]


In [24]:
print(arr3[mask == False])      # Los que no cumplan la condicion; mask = ((arr3 % 3) != 0)

[ 10  11  13  14  16  17  19  20  22  23  25  26  28  29  31  32  34  35
  37  38  40  41  43  44  46  47  49  50  52  53  55  56  58  59  61  62
  64  65  67  68  70  71  73  74  76  77  79  80  82  83  85  86  88  89
  91  92  94  95  97  98 100]


In [25]:
print(arr3 % 3)

[1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1
 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2
 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]


In [26]:
print(arr3[(arr3 % 3 ) == 0]) 

[12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81
 84 87 90 93 96 99]


In [27]:
mask1 = arr3 > 43
print(mask1)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True]


In [32]:
print(arr3[mask & mask1])    # -> AND == &
print('-'*55)
print(arr3[mask | mask1])    # -> OR == |

[45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99]
-------------------------------------------------------
[ 12  15  18  21  24  27  30  33  36  39  42  44  45  46  47  48  49  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [36]:
arr = np.array([3, 5, 7, 9, 11, 15, 18, 22])
arr2 = arr[-4:-2]
print(arr2)

[11 15]


In [54]:
zeros1 = np.zeros(shape=(5,10), dtype=int)
print(zeros1)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [38]:
zeros2 = np.full(shape=(5,10), fill_value=0)
print(zeros2)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [43]:
zeros3 = np.linspace(start=0,stop=0,num=50, dtype=int).reshape(5,10)
print(zeros3)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [44]:
#           array[fila,columna]   -> array[desde:hasta,desde:hasta]

print(zeros1[1,2])

0


In [49]:
print(zeros1[:,0:4])

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [52]:
print(zeros1[0:2])

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [55]:
zeros1[1] += 1
zeros1[3] += 1
print(zeros1)

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]]


In [57]:
zeros2[[1,3]] = 1
print(zeros2)

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]]


In [58]:
zeros1[:,2] = 2
zeros1[:,7] = 2
print(zeros1)

[[0 0 2 0 0 0 0 2 0 0]
 [1 1 2 1 1 1 1 2 1 1]
 [0 0 2 0 0 0 0 2 0 0]
 [1 1 2 1 1 1 1 2 1 1]
 [0 0 2 0 0 0 0 2 0 0]]


In [59]:
zeros2[:,[2,7]] = 2
print(zeros2)

[[0 0 2 0 0 0 0 2 0 0]
 [1 1 2 1 1 1 1 2 1 1]
 [0 0 2 0 0 0 0 2 0 0]
 [1 1 2 1 1 1 1 2 1 1]
 [0 0 2 0 0 0 0 2 0 0]]


In [66]:
zeros3[[1,3]] = np.ones(10,dtype=int)
print(zeros3)

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]]


In [67]:
matrix = np.matrix(zeros1)
print(type(matrix))
print(type(zeros1))

<class 'numpy.matrix'>
<class 'numpy.ndarray'>


In [68]:
print(matrix)

[[0 0 2 0 0 0 0 2 0 0]
 [1 1 2 1 1 1 1 2 1 1]
 [0 0 2 0 0 0 0 2 0 0]
 [1 1 2 1 1 1 1 2 1 1]
 [0 0 2 0 0 0 0 2 0 0]]


**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html

In [17]:
a = np.random.random((4,2,3)) * 100 + 100
a

array([[[137.12277219, 187.22289567, 153.95764007],
        [175.21869487, 188.10311988, 118.02508687]],

       [[157.58773537, 166.74585121, 134.96866874],
        [128.3807111 , 188.91447629, 150.68622952]],

       [[168.77296873, 117.90287547, 115.19825164],
        [123.86197814, 172.33144425, 165.7329653 ]],

       [[157.35784374, 121.82035838, 100.01848734],
        [195.39977874, 188.95736542, 121.54200787]]])

In [18]:
a = np.random.random((4,4))

In [19]:
a

array([[0.48673571, 0.50465005, 0.33227167, 0.86611167],
       [0.14502147, 0.13692842, 0.56804006, 0.89177045],
       [0.78692331, 0.25942502, 0.88516122, 0.32876297],
       [0.78919257, 0.64347772, 0.02402004, 0.66363368]])

In [20]:
a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=np.int8)

In [115]:
a

array([[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]], dtype=int16)

In [21]:
a.sum()

519

In [22]:
a.std()

23.924904214367643

In [23]:
a.sort(axis=1)

In [24]:
a

array([[-56,   5,  10,  30,  45,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50]], dtype=int8)

In [25]:
a.sort(axis=0)
a

array([[-56,   5,  10,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  45,  50]], dtype=int8)

In [26]:
a[1:3,0:3]

array([[ 0,  5, 20],
       [ 0,  5, 20]], dtype=int8)

In [27]:
l =   [[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]]

In [28]:
a = np.array([l])

In [31]:
a.shape

(1, 4, 6)

In [32]:
a.reshape(24)

array([ 10, 200,  30,  45,   5, 100,   5,  20,  30,  40,  50,   0,   5,
        20,  30,  40,  50,   0,   5,  20,  30,  40,  50,   0])

In [33]:
a = np.matrix([[1,2,3,4,5,6]]) 
print(a) 

[[1 2 3 4 5 6]]


In [34]:
b = np.matrix([[1],[2],[3],[4],[5],[6]]) 
print(b) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [35]:
c = a * b 
print(c) 

[[91]]


In [36]:
d = b * a 
print(d)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]


In [69]:
%pip install pandas

In [70]:
import pandas as pd

In [71]:
lista = ['Matemáticas','Inglés','Economía','Historia','Programación']

serie = pd.Series(data=lista,dtype='string')
print(serie)

0     Matemáticas
1          Inglés
2        Economía
3        Historia
4    Programación
dtype: string


In [72]:
serie[4]

'Programación'

In [73]:
dicc = {'Matemáticas':6.0,
        'Historia':9.0,
        'Economía':5.0,
        'Inglés':8.0,
        'Programación':10.0}
serie = pd.Series(data=dicc)
print(serie)

Matemáticas      6.0
Historia         9.0
Economía         5.0
Inglés           8.0
Programación    10.0
dtype: float64


In [74]:
serie['Historia']

9.0

In [75]:
serie['Programación']

10.0

In [76]:
serie[4]

10.0

In [77]:
print(serie[['Historia','Inglés']])

Historia    9.0
Inglés      8.0
dtype: float64


In [78]:
print(serie.values)
print(serie.dtype)
print(serie.index)
print(serie.size)

[ 6.  9.  5.  8. 10.]
float64
Index(['Matemáticas', 'Historia', 'Economía', 'Inglés', 'Programación'], dtype='object')
5


In [79]:
tupla = (1,2,3,4,5,6,7,89,9,'Hola Mundo!')

serie2 = pd.Series(data=tupla, dtype='string', index=[1,2,3,4,5,6,7,8,9,10])
print(serie2)

1               1
2               2
3               3
4               4
5               5
6               6
7               7
8              89
9               9
10    Hola Mundo!
dtype: string


In [84]:
s = pd.Series([1,1,1,1,2,2,2,3,3,4], dtype=float)
print(s)

0    1.0
1    1.0
2    1.0
3    1.0
4    2.0
5    2.0
6    2.0
7    3.0
8    3.0
9    4.0
dtype: float64


In [85]:
print(s.count())
print(s.sum())
print(s.cumsum())

10
20.0
0     1.0
1     2.0
2     3.0
3     4.0
4     6.0
5     8.0
6    10.0
7    13.0
8    16.0
9    20.0
dtype: float64


In [86]:
s.value_counts()  # Contabiliza los valores

1.0    4
2.0    3
3.0    2
4.0    1
dtype: int64

In [87]:
print(s.min())
print(s.max())

1.0
4.0


In [88]:
s.describe()

count    10.000000
mean      2.000000
std       1.054093
min       1.000000
25%       1.000000
50%       2.000000
75%       2.750000
max       4.000000
dtype: float64

In [89]:
print(s.mean())         # Media aritmetica o promedio
print(s.median())       # Mediana
print(s.std())          # Desviacion estandar

2.0
2.0
1.0540925533894598


In [90]:
s = pd.Series([1,2,3,4,5,6,7,8,9], dtype=float)
print(s)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    7.0
7    8.0
8    9.0
dtype: float64


In [91]:
s * 2

0     2.0
1     4.0
2     6.0
3     8.0
4    10.0
5    12.0
6    14.0
7    16.0
8    18.0
dtype: float64

In [92]:
s % 2

0    1.0
1    0.0
2    1.0
3    0.0
4    1.0
5    0.0
6    1.0
7    0.0
8    1.0
dtype: float64

In [93]:
s // 2

0    0.0
1    1.0
2    1.0
3    2.0
4    2.0
5    3.0
6    3.0
7    4.0
8    4.0
dtype: float64

In [94]:
from math import log

s.apply(log)

0    0.000000
1    0.693147
2    1.098612
3    1.386294
4    1.609438
5    1.791759
6    1.945910
7    2.079442
8    2.197225
dtype: float64

In [95]:
mask = (s % 2) == 0
print(mask)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7     True
8    False
dtype: bool


In [101]:
print(s[mask == False])

0    1.0
2    3.0
4    5.0
6    7.0
8    9.0
dtype: float64


In [97]:
print(s[s % 2 == 0])

1    2.0
3    4.0
5    6.0
7    8.0
dtype: float64


In [100]:
s[s > 5].apply(np.log)

5    1.791759
6    1.945910
7    2.079442
8    2.197225
dtype: float64

In [105]:
s.sort_values(ascending=False)          # Ordena por valores

8    9.0
7    8.0
6    7.0
5    6.0
4    5.0
3    4.0
2    3.0
1    2.0
0    1.0
dtype: float64

In [108]:
s.sort_index(ascending=False)           # Ordena por indices

8    9.0
7    8.0
6    7.0
5    6.0
4    5.0
3    4.0
2    3.0
1    2.0
0    1.0
dtype: float64

In [116]:
# np.NaN -> None -> Null    != ''

s = pd.Series([1,2,3,None,np.NaN,'d'])
print(s)

0       1
1       2
2       3
3    None
4     NaN
5       d
dtype: object


In [117]:
s = s.dropna()  # Eliminar valores nulos

In [118]:
s

0    1
1    2
2    3
5    d
dtype: object

In [126]:
dicc = {'Nombre':['Maria','Antonio','Luis','Carmen'],
        'Edad':[18,25,21,24],
        'Grado':['Economía','Economía','Medicina','Arquitectura'],
        'Correo':['maria@gmail.com','antonio@gmail.com','luis@yahoo.com','carmen@hotmail.com']}

df = pd.DataFrame(data=dicc, index=range(1,5))
df

Nombre  Edad         Grado              Correo
1    Maria    18      Economía     maria@gmail.com
2  Antonio    25      Economía   antonio@gmail.com
3     Luis    21      Medicina      luis@yahoo.com
4   Carmen    24  Arquitectura  carmen@hotmail.com

In [123]:
lista = [['Maria',18],['Antonio',25],['Luis',21],['Carmen',24]]
df1 = pd.DataFrame(data=lista, columns=['Nombre','Edad'])
df1

Nombre  Edad
0    Maria    18
1  Antonio    25
2     Luis    21
3   Carmen    24

In [125]:
lista_dicc = [{'Nombre':'Maria','Edad':18},
              {'Nombre':'Antonio','Edad':25},
              {'Nombre':'Luis','Edad':21},
              {'Nombre':'Carmen','Edad':24}]

df2 = pd.DataFrame(lista_dicc)
df2

Nombre  Edad
0    Maria    18
1  Antonio    25
2     Luis    21
3   Carmen    24

In [133]:
df3 = pd.DataFrame(np.random.randn(4,4), columns=['a','b','c','d'], index=['z','x','w','y'])
df3

a         b         c         d
z -2.140010  0.580523 -0.835046 -0.936316
x -0.780169  0.317198 -0.340790  0.379802
w -0.723308 -0.120180 -2.456268 -1.303150
y  0.607255  0.093810 -0.443600 -0.374271

In [134]:
"""
CSV ->  Comma Separated Values   .csv  -> pd.read_csv

Excel -> .xlsx, .xlx   -> pd.read_excel

PATHS O RUTAS:

# NO USAR EN EL EXAMEN
ruta completa : C:\Users\Gonzalo Posse\Desktop\Desk\Henry-Mentor\Instructor\Data FT-17\DS-M1\M1\Clase 03\datasets\Emisiones_CO2.csv


# SI VA EN EL EXAMEN
ruta relativa : datasets/Emisiones_CO2.csv          

"""

df4 = pd.read_csv('datasets/Emisiones_CO2.csv', sep='|', encoding='latin-1')
df4

Código de país Nombre del país                   Región   Año  CO2 (kt)  \
0                ABW           Aruba  América Latina y Caribe  1960       NaN   
1                ABW           Aruba  América Latina y Caribe  1961       NaN   
2                ABW           Aruba  América Latina y Caribe  1962       NaN   
3                ABW           Aruba  América Latina y Caribe  1963       NaN   
4                ABW           Aruba  América Latina y Caribe  1964       NaN   
...              ...             ...                      ...   ...       ...   
11122            ZWE        Zimbabue      África subsahariana  2007  9.732,22   
11123            ZWE        Zimbabue      África subsahariana  2008  7.682,37   
11124            ZWE        Zimbabue      África subsahariana  2009  8.239,75   
11125            ZWE        Zimbabue      África subsahariana  2010  9.028,15   
11126            ZWE        Zimbabue      África subsahariana  2011  9.860,56   

      CO2 per cápita (toneladas métricas)  
0                                     NaN  
1                                     NaN  
2                                     NaN  
3                                     NaN  
4                                     NaN  
...                                   ...  
11122                         0,731866885  
11123                         0,569255428  
11124                         0,600521157  
11125                         0,646072745  
11126                         0,691697897  

[11127 rows x 6 columns]

In [139]:
df4.to_excel('Emisiones_C02.xlsx', index=False)

In [140]:
df5 = pd.read_excel('Emisiones_C02.xlsx')

In [141]:
df5

Código de país Nombre del país                   Región   Año  CO2 (kt)  \
0                ABW           Aruba  América Latina y Caribe  1960       NaN   
1                ABW           Aruba  América Latina y Caribe  1961       NaN   
2                ABW           Aruba  América Latina y Caribe  1962       NaN   
3                ABW           Aruba  América Latina y Caribe  1963       NaN   
4                ABW           Aruba  América Latina y Caribe  1964       NaN   
...              ...             ...                      ...   ...       ...   
11122            ZWE        Zimbabue      África subsahariana  2007  9.732,22   
11123            ZWE        Zimbabue      África subsahariana  2008  7.682,37   
11124            ZWE        Zimbabue      África subsahariana  2009  8.239,75   
11125            ZWE        Zimbabue      África subsahariana  2010  9.028,15   
11126            ZWE        Zimbabue      África subsahariana  2011  9.860,56   

      CO2 per cápita (toneladas métricas)  
0                                     NaN  
1                                     NaN  
2                                     NaN  
3                                     NaN  
4                                     NaN  
...                                   ...  
11122                         0,731866885  
11123                         0,569255428  
11124                         0,600521157  
11125                         0,646072745  
11126                         0,691697897  

[11127 rows x 6 columns]

In [142]:
df5 = pd.read_csv('https://raw.githubusercontent.com/lucav48/data-science-dataset/master/pandas/dataset/titanic.csv')
df5

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [144]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11127 entries, 0 to 11126
Data columns (total 6 columns):
 #   Column                               Non-Null Count  Dtype 
---  ------                               --------------  ----- 
 0   Código de país                       11127 non-null  object
 1   Nombre del país                      11127 non-null  object
 2   Región                               11127 non-null  object
 3   Año                                  11127 non-null  int64 
 4   CO2 (kt)                             9032 non-null   object
 5   CO2 per cápita (toneladas métricas)  9029 non-null   object
dtypes: int64(1), object(5)
memory usage: 521.7+ KB


In [153]:
df4.columns.to_list()

['Código de país',
 'Nombre del país',
 'Región',
 'Año',
 'CO2 (kt)',
 'CO2 per cápita (toneladas métricas)']

In [146]:
df4.index

RangeIndex(start=0, stop=11127, step=1)

In [147]:
df4.shape

(11127, 6)

In [148]:
df4.size

66762

In [156]:
df4.dtypes

Código de país                         object
Nombre del país                        object
Región                                 object
Año                                     int64
CO2 (kt)                               object
CO2 per cápita (toneladas métricas)    object
dtype: object

In [159]:
df4.head()          # n por defecto = 5

Código de país Nombre del país                   Región   Año CO2 (kt)  \
0            ABW           Aruba  América Latina y Caribe  1960      NaN   
1            ABW           Aruba  América Latina y Caribe  1961      NaN   
2            ABW           Aruba  América Latina y Caribe  1962      NaN   
3            ABW           Aruba  América Latina y Caribe  1963      NaN   
4            ABW           Aruba  América Latina y Caribe  1964      NaN   

  CO2 per cápita (toneladas métricas)  
0                                 NaN  
1                                 NaN  
2                                 NaN  
3                                 NaN  
4                                 NaN

In [161]:
df4.tail(1)          # n por defecto = 5

Código de país Nombre del país               Región   Año  CO2 (kt)  \
11126            ZWE        Zimbabue  África subsahariana  2011  9.860,56   

      CO2 per cápita (toneladas métricas)  
11126                         0,691697897

In [165]:
df4['Nombre del país']

0           Aruba
1           Aruba
2           Aruba
3           Aruba
4           Aruba
           ...   
11122    Zimbabue
11123    Zimbabue
11124    Zimbabue
11125    Zimbabue
11126    Zimbabue
Name: Nombre del país, Length: 11127, dtype: object

In [167]:
df4.Región

0        América Latina y Caribe
1        América Latina y Caribe
2        América Latina y Caribe
3        América Latina y Caribe
4        América Latina y Caribe
                  ...           
11122        África subsahariana
11123        África subsahariana
11124        África subsahariana
11125        África subsahariana
11126        África subsahariana
Name: Región, Length: 11127, dtype: object

In [169]:
direccion = ['Calle 2', 'Calle 3', 'Calle 2', 'Calle 8']

df['Direccion'] = direccion
df

Nombre  Edad         Grado              Correo Direccion
1    Maria    18      Economía     maria@gmail.com   Calle 2
2  Antonio    25      Economía   antonio@gmail.com   Calle 3
3     Luis    21      Medicina      luis@yahoo.com   Calle 2
4   Carmen    24  Arquitectura  carmen@hotmail.com   Calle 8

In [174]:
df5['Age'] ** 110

0      4.639753e+147
1      5.973043e+173
2      4.436784e+155
3      7.038577e+169
4      7.038577e+169
           ...      
886    2.818474e+157
887    4.601465e+140
888              NaN
889    4.436784e+155
890    3.685510e+165
Name: Age, Length: 891, dtype: float64

In [175]:
df4['Año'].value_counts()

1986    214
1961    214
1988    214
1989    214
1990    214
1991    214
1992    214
1993    214
1994    214
1995    214
1996    214
1997    214
1998    214
1999    214
2000    214
2001    214
2002    214
2003    214
2004    214
2005    214
2006    214
2007    214
2008    214
2009    214
2010    214
1987    214
2011    214
1985    214
1972    214
1962    214
1963    214
1964    214
1965    214
1966    214
1967    214
1968    214
1969    214
1970    214
1971    214
1973    214
1984    214
1974    214
1975    214
1976    214
1977    214
1978    214
1979    214
1980    214
1981    214
1982    214
1983    214
1960    213
Name: Año, dtype: int64

In [177]:
df4['Año'].apply(np.sqrt)

0        44.271887
1        44.283180
2        44.294469
3        44.305756
4        44.317040
           ...    
11122    44.799554
11123    44.810713
11124    44.821870
11125    44.833024
11126    44.844175
Name: Año, Length: 11127, dtype: float64

In [178]:
df_time = pd.DataFrame({'Name':['Maria','Carlos','Carmen'], 'Nacimiento':['05-03-2000','20-05-2001','10-12-1999']})
df_time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Name        3 non-null      object
 1   Nacimiento  3 non-null      object
dtypes: object(2)
memory usage: 180.0+ bytes


In [179]:
df_time.Nacimiento = pd.to_datetime(df_time.Nacimiento, format='%d-%m-%Y')
df_time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   Name        3 non-null      object        
 1   Nacimiento  3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(1)
memory usage: 180.0+ bytes


In [180]:
df_time

Name Nacimiento
0   Maria 2000-03-05
1  Carlos 2001-05-20
2  Carmen 1999-12-10

In [184]:
df4.rename(columns={'Código de país':'cod_pais','Nombre del país':'nom_pais','CO2 (kt)':'co2','CO2 per cápita (toneladas métricas)':'co2_percapita'}, inplace=True)

In [186]:
df4.rename(index={0:1000000, 1:2000000,3:3000000})

cod_pais  nom_pais                   Región   Año       co2  \
1000000      ABW     Aruba  América Latina y Caribe  1960       NaN   
2000000      ABW     Aruba  América Latina y Caribe  1961       NaN   
2            ABW     Aruba  América Latina y Caribe  1962       NaN   
3000000      ABW     Aruba  América Latina y Caribe  1963       NaN   
4            ABW     Aruba  América Latina y Caribe  1964       NaN   
...          ...       ...                      ...   ...       ...   
11122        ZWE  Zimbabue      África subsahariana  2007  9.732,22   
11123        ZWE  Zimbabue      África subsahariana  2008  7.682,37   
11124        ZWE  Zimbabue      África subsahariana  2009  8.239,75   
11125        ZWE  Zimbabue      África subsahariana  2010  9.028,15   
11126        ZWE  Zimbabue      África subsahariana  2011  9.860,56   

        co2_percapita  
1000000           NaN  
2000000           NaN  
2                 NaN  
3000000           NaN  
4                 NaN  
...               ...  
11122     0,731866885  
11123     0,569255428  
11124     0,600521157  
11125     0,646072745  
11126     0,691697897  

[11127 rows x 6 columns]

In [190]:
df.reindex(index=[4,2,1,3])

Nombre  Edad         Grado              Correo Direccion
4   Carmen    24  Arquitectura  carmen@hotmail.com   Calle 8
2  Antonio    25      Economía   antonio@gmail.com   Calle 3
1    Maria    18      Economía     maria@gmail.com   Calle 2
3     Luis    21      Medicina      luis@yahoo.com   Calle 2

In [191]:
direccion = df.pop('Direccion')
df

Nombre  Edad         Grado              Correo
1    Maria    18      Economía     maria@gmail.com
2  Antonio    25      Economía   antonio@gmail.com
3     Luis    21      Medicina      luis@yahoo.com
4   Carmen    24  Arquitectura  carmen@hotmail.com

In [197]:
df['Direccion'] = direccion

In [195]:
del df['Direccion']

In [199]:
df.reset_index()

index   Nombre  Edad         Grado              Correo Direccion
0      1    Maria    18      Economía     maria@gmail.com   Calle 2
1      2  Antonio    25      Economía   antonio@gmail.com   Calle 3
2      3     Luis    21      Medicina      luis@yahoo.com   Calle 2
3      4   Carmen    24  Arquitectura  carmen@hotmail.com   Calle 8

In [201]:
df4.drop([0,1,2,3,4],axis=0,inplace=True)

In [203]:
df4.reset_index()

index cod_pais  nom_pais                   Región   Año       co2  \
0          5      ABW     Aruba  América Latina y Caribe  1965       NaN   
1          6      ABW     Aruba  América Latina y Caribe  1966       NaN   
2          7      ABW     Aruba  América Latina y Caribe  1967       NaN   
3          8      ABW     Aruba  América Latina y Caribe  1968       NaN   
4          9      ABW     Aruba  América Latina y Caribe  1969       NaN   
...      ...      ...       ...                      ...   ...       ...   
11117  11122      ZWE  Zimbabue      África subsahariana  2007  9.732,22   
11118  11123      ZWE  Zimbabue      África subsahariana  2008  7.682,37   
11119  11124      ZWE  Zimbabue      África subsahariana  2009  8.239,75   
11120  11125      ZWE  Zimbabue      África subsahariana  2010  9.028,15   
11121  11126      ZWE  Zimbabue      África subsahariana  2011  9.860,56   

      co2_percapita  
0               NaN  
1               NaN  
2               NaN  
3               NaN  
4               NaN  
...             ...  
11117   0,731866885  
11118   0,569255428  
11119   0,600521157  
11120   0,646072745  
11121   0,691697897  

[11122 rows x 7 columns]

In [207]:
df_na = df4.dropna()
df4

cod_pais  nom_pais                   Región   Año       co2  \
5          ABW     Aruba  América Latina y Caribe  1965       NaN   
6          ABW     Aruba  América Latina y Caribe  1966       NaN   
7          ABW     Aruba  América Latina y Caribe  1967       NaN   
8          ABW     Aruba  América Latina y Caribe  1968       NaN   
9          ABW     Aruba  América Latina y Caribe  1969       NaN   
...        ...       ...                      ...   ...       ...   
11122      ZWE  Zimbabue      África subsahariana  2007  9.732,22   
11123      ZWE  Zimbabue      África subsahariana  2008  7.682,37   
11124      ZWE  Zimbabue      África subsahariana  2009  8.239,75   
11125      ZWE  Zimbabue      África subsahariana  2010  9.028,15   
11126      ZWE  Zimbabue      África subsahariana  2011  9.860,56   

      co2_percapita  
5               NaN  
6               NaN  
7               NaN  
8               NaN  
9               NaN  
...             ...  
11122   0,731866885  
11123   0,569255428  
11124   0,600521157  
11125   0,646072745  
11126   0,691697897  

[11122 rows x 6 columns]

In [ ]:
' N/D -> No Data'

In [206]:
df_na

cod_pais  nom_pais                   Región   Año       co2  \
26         ABW     Aruba  América Latina y Caribe  1986   179,683   
27         ABW     Aruba  América Latina y Caribe  1987   447,374   
28         ABW     Aruba  América Latina y Caribe  1988   612,389   
29         ABW     Aruba  América Latina y Caribe  1989   649,059   
30         ABW     Aruba  América Latina y Caribe  1990  1.840,83   
...        ...       ...                      ...   ...       ...   
11122      ZWE  Zimbabue      África subsahariana  2007  9.732,22   
11123      ZWE  Zimbabue      África subsahariana  2008  7.682,37   
11124      ZWE  Zimbabue      África subsahariana  2009  8.239,75   
11125      ZWE  Zimbabue      África subsahariana  2010  9.028,15   
11126      ZWE  Zimbabue      África subsahariana  2011  9.860,56   

      co2_percapita  
26      2,868319392  
27      7,234964017  
28     10,026507523  
29     10,634732599  
30     29,620164768  
...             ...  
11122   0,731866885  
11123   0,569255428  
11124   0,600521157  
11125   0,646072745  
11126   0,691697897  

[9029 rows x 6 columns]

In [210]:
df.sort_values('Edad',ascending=False)

Nombre  Edad         Grado              Correo Direccion
2  Antonio    25      Economía   antonio@gmail.com   Calle 3
4   Carmen    24  Arquitectura  carmen@hotmail.com   Calle 8
3     Luis    21      Medicina      luis@yahoo.com   Calle 2
1    Maria    18      Economía     maria@gmail.com   Calle 2

In [211]:
df.sort_index(ascending=False)

Nombre  Edad         Grado              Correo Direccion
4   Carmen    24  Arquitectura  carmen@hotmail.com   Calle 8
3     Luis    21      Medicina      luis@yahoo.com   Calle 2
2  Antonio    25      Economía   antonio@gmail.com   Calle 3
1    Maria    18      Economía     maria@gmail.com   Calle 2

In [213]:
df4[df4['Región'] == 'América Latina y Caribe']

cod_pais                  nom_pais                   Región   Año  co2  \
5          ABW                     Aruba  América Latina y Caribe  1965  NaN   
6          ABW                     Aruba  América Latina y Caribe  1966  NaN   
7          ABW                     Aruba  América Latina y Caribe  1967  NaN   
8          ABW                     Aruba  América Latina y Caribe  1968  NaN   
9          ABW                     Aruba  América Latina y Caribe  1969  NaN   
...        ...                       ...                      ...   ...  ...   
10654      VIR  Islas Vírgenes (EE. UU.)  América Latina y Caribe  2007  NaN   
10655      VIR  Islas Vírgenes (EE. UU.)  América Latina y Caribe  2008  NaN   
10656      VIR  Islas Vírgenes (EE. UU.)  América Latina y Caribe  2009  NaN   
10657      VIR  Islas Vírgenes (EE. UU.)  América Latina y Caribe  2010  NaN   
10658      VIR  Islas Vírgenes (EE. UU.)  América Latina y Caribe  2011  NaN   

      co2_percapita  
5               NaN  
6               NaN  
7               NaN  
8               NaN  
9               NaN  
...             ...  
10654           NaN  
10655           NaN  
10656           NaN  
10657           NaN  
10658           NaN  

[2127 rows x 6 columns]

In [214]:
df4[df4['Año'] == 2010]

cod_pais                       nom_pais  \
50         ABW                          Aruba   
102        AND                        Andorra   
154        AFG                     Afganistán   
206        AGO                         Angola   
258        ALB                        Albania   
...        ...                            ...   
10917      YEM                          Yemen   
10969      ZAF                      Sudáfrica   
11021      COD  Congo (República Democrática)   
11073      ZMB                         Zambia   
11125      ZWE                       Zimbabue   

                                Región   Año         co2 co2_percapita  
50             América Latina y Caribe  2010    2.456,89  24,182702245  
102              Europa y Asia Central  2010     517,047    6,12477049  
154                        Sur de Asia  2010    8.470,77   0,302936388  
206                África subsahariana  2010   29.743,04   1,401654169  
258              Europa y Asia Central  2010    4.415,07   1,515632053  
...                                ...   ...         ...           ...  
10917  Oriente Medio y Norte de África  2010   25.716,67   1,090060254  
10969              África subsahariana  2010  454.950,02   8,957153524  
11021              África subsahariana  2010    3.252,63   0,049328064  
11073              África subsahariana  2010    2.673,24   0,192078658  
11125              África subsahariana  2010    9.028,15   0,646072745  

[214 rows x 6 columns]

In [219]:
df4[(df4['Región'] == 'América Latina y Caribe') & (df4['Año'] == 2010)].dropna()

cod_pais                      nom_pais                   Región   Año  \
50         ABW                         Aruba  América Latina y Caribe  2010   
362        ARG                     Argentina  América Latina y Caribe  2010   
518        ATG             Antigua y Barbuda  América Latina y Caribe  2010   
1090       BHS                       Bahamas  América Latina y Caribe  2010   
1246       BLZ                        Belice  América Latina y Caribe  2010   
1350       BOL                       Bolivia  América Latina y Caribe  2010   
1402       BRA                        Brasil  América Latina y Caribe  2010   
1454       BRB                      Barbados  América Latina y Caribe  2010   
1870       CHL                         Chile  América Latina y Caribe  2010   
2130       COL                      Colombia  América Latina y Caribe  2010   
2286       CRI                    Costa Rica  América Latina y Caribe  2010   
2338       CUB                          Cuba  América Latina y Caribe  2010   
2442       CYM                  Islas Caimán  América Latina y Caribe  2010   
2702       DMA                      Dominica  América Latina y Caribe  2010   
2806       DOM          República Dominicana  América Latina y Caribe  2010   
2910       ECU                       Ecuador  América Latina y Caribe  2010   
3950       GRD                       Granada  América Latina y Caribe  2010   
4054       GTM                     Guatemala  América Latina y Caribe  2010   
4158       GUY                        Guyana  América Latina y Caribe  2010   
4262       HND                      Honduras  América Latina y Caribe  2010   
4366       HTI                         Haití  América Latina y Caribe  2010   
4938       JAM                       Jamaica  América Latina y Caribe  2010   
5354       KNA        San Cristóbal y Nieves  América Latina y Caribe  2010   
5770       LCA                   Santa Lucía  América Latina y Caribe  2010   
6498       MEX                        México  América Latina y Caribe  2010   
7434       NIC                     Nicaragua  América Latina y Caribe  2010   
7798       PAN                        Panamá  América Latina y Caribe  2010   
7850       PER                          Perú  América Latina y Caribe  2010   
8266       PRY                      Paraguay  América Latina y Caribe  2010   
8890       SLV                   El Salvador  América Latina y Caribe  2010   
9201       SUR                       Surinam  América Latina y Caribe  2010   
9617       TCA         Islas Turcas y Caicos  América Latina y Caribe  2010   
10033      TTO             Trinidad y Tobago  América Latina y Caribe  2010   
10397      URY                       Uruguay  América Latina y Caribe  2010   
10553      VCT  San Vicente y las Granadinas  América Latina y Caribe  2010   
10605      VEN                     Venezuela  América Latina y Caribe  2010   

              co2 co2_percapita  
50       2.456,89  24,182702245  
362    179.000,94   4,342272052  
518       524,381   6,011268671  
1090     2.464,22   6,829321287  
1246      553,717   1,721708659  
1350    15.350,06   1,547659087  
1402   419.754,16   2,113414545  
1454     1.518,14   5,430338453  
1870    72.258,24    4,24672531  
2130    78.583,81   1,711390678  
2286     7.568,69   1,665177867  
2338    38.360,49   3,392291813  
2442      564,718  10,173449351  
2702      135,679   1,906487557  
2806    21.363,94   2,158413689  
2910    34.249,78   2,293303404  
3950      260,357   2,487241705  
4054    11.367,70   0,771619509  
4158     1.719,82   2,282864015  
4262     8.107,74   1,080473355  
4366     2.119,53   0,211960718  
4938     7.190,99   2,672410756  
5354      260,357   4,973200642  
5770       403,37   2,273826502  
6498   445.063,79   3,752090816  
7434     4.624,09   0,805909906  
7798     8.866,81   2,449051597  
7850    57.857,93   1,969722449  
8266     5.075,13   0,817267073  
8890     6.307,24   1,044537988  
9201     2.394,55   4,621427

In [226]:
df.iloc[1,3]                # Accede mediante posiciones

'antonio@gmail.com'

In [224]:
df

Nombre  Edad         Grado              Correo Direccion
1    Maria    18      Economía     maria@gmail.com   Calle 2
2  Antonio    25      Economía   antonio@gmail.com   Calle 3
3     Luis    21      Medicina      luis@yahoo.com   Calle 2
4   Carmen    24  Arquitectura  carmen@hotmail.com   Calle 8

In [227]:
df.loc[1,'Correo']                       # Accede mediante etiquetas

'maria@gmail.com'

In [228]:
df.Edad

1    18
2    25
3    21
4    24
Name: Edad, dtype: int64

In [229]:
df['Edad']

1    18
2    25
3    21
4    24
Name: Edad, dtype: int64

In [230]:
df['Edad'].count()

4

In [231]:
df['Edad'].sum()

88

In [232]:
df['Edad'].cumsum()

1    18
2    43
3    64
4    88
Name: Edad, dtype: int64

In [234]:
print(df['Edad'].mean())
print(df['Edad'].median())
print(df['Edad'].std())
print(df['Edad'].var())

22.0
22.5
3.1622776601683795
10.0


In [235]:
df.describe()

Edad
count   4.000000
mean   22.000000
std     3.162278
min    18.000000
25%    20.250000
50%    22.500000
75%    24.250000
max    25.000000

In [236]:
df.describe(include='all')

Nombre       Edad     Grado           Correo Direccion
count       4   4.000000         4                4         4
unique      4        NaN         3                4         3
top     Maria        NaN  Economía  maria@gmail.com   Calle 2
freq        1        NaN         2                1         2
mean      NaN  22.000000       NaN              NaN       NaN
std       NaN   3.162278       NaN              NaN       NaN
min       NaN  18.000000       NaN              NaN       NaN
25%       NaN  20.250000       NaN              NaN       NaN
50%       NaN  22.500000       NaN              NaN       NaN
75%       NaN  24.250000       NaN              NaN       NaN
max       NaN  25.000000       NaN              NaN       NaN

In [239]:
df4.groupby(by='cod_pais').count()

nom_pais  Región  Año  co2  co2_percapita
cod_pais                                           
ABW             47      47   47   26             26
AFG             52      52   52   52             52
AGO             52      52   52   52             52
ALB             52      52   52   52             52
AND             52      52   52   17             17
...            ...     ...  ...  ...            ...
WSM             52      52   52   52             52
YEM             52      52   52   52             52
ZAF             52      52   52   52             52
ZMB             52      52   52   48             48
ZWE             52      52   52   48             48

[214 rows x 5 columns]

In [245]:
df4.groupby(by='cod_pais').agg(np.mean)

C:\Users\Gonzalo Posse\AppData\Local\Temp\ipykernel_20816\369429971.py:1: FutureWarning: The operation <function mean at 0x000002A7E35C2480> failed on a column. If any error is raised, this will raise an exception in a future version of pandas. Drop these columns to avoid this warning.
  df4.groupby(by='cod_pais').agg(np.mean)


Año
cod_pais        
ABW       1988.0
AFG       1985.5
AGO       1985.5
ALB       1985.5
AND       1985.5
...          ...
WSM       1985.5
YEM       1985.5
ZAF       1985.5
ZMB       1985.5
ZWE       1985.5

[214 rows x 1 columns]

In [248]:
df4_2 = df4.pivot(index='cod_pais',columns='Año',values='co2')
df4_2

Año            1960        1961        1962        1963        1964  \
cod_pais                                                              
ABW             NaN         NaN         NaN         NaN         NaN   
AFG         414,371     491,378     689,396     707,731     839,743   
AGO          550,05     454,708    1.180,77    1.151,44    1.224,78   
ALB        2.024,18    2.280,87    2.464,22    2.082,86    2.016,85   
AND             NaN         NaN         NaN         NaN         NaN   
...             ...         ...         ...         ...         ...   
WSM          14,668      18,335      18,335      22,002      25,669   
YEM        3.634,00    2.665,91    3.887,02    2.918,93    3.634,00   
ZAF       97.934,57  102.213,96  105.767,28  109.826,65  119.657,88   
ZMB             NaN         NaN         NaN         NaN    3.278,30   
ZWE             NaN         NaN         NaN         NaN    4.473,74   

Año             1965        1966        1967        1968        1969  ...  \
cod_pais                                                              ...   
ABW              NaN         NaN         NaN         NaN         NaN  ...   
AFG         1.008,43    1.092,77    1.283,45    1.224,78     942,419  ...   
AGO         1.188,11    1.554,81     993,757    1.672,15    2.786,92  ...   
ALB         2.174,53    2.552,23    2.680,58    3.072,95    3.245,30  ...   
AND              NaN         NaN         NaN         NaN         NaN  ...   
...              ...         ...         ...         ...         ...  ...   
WSM           29,336      25,669      25,669      29,336      29,336  ...   
YEM         3.931,02    3.465,32    3.054,61   11.646,39    4.679,09  ...   
ZAF       128.260,66  128.356,00  133.885,84  138.084,55  143.280,69  ...   
ZMB         3.916,36    3.501,99    4.792,77    4.572,75    4.275,72  ...   
ZWE         5.214,47    6.046,88    5.298,82    6.384,25    6.750,95  ...   

Año             2002        2003        2004        2005        2006  \
cod_pais                                                               
ABW         2.372,55    2.416,55    2.420,22    2.497,23    2.497,23   
AFG          894,748    1.037,76     957,087    1.338,46    1.657,48   
AGO        12.665,82    9.064,82   18.793,38   19.156,41   22.266,02   
ALB         3.751,34    4.294,06    4.165,71    4.253,72    3.865,02   
AND          531,715     535,382     564,718     575,719     546,383   
...              ...         ...         ...         ...         ...   
WSM          143,013     150,347     161,348     168,682     176,016   
YEM        15.764,43   17.304,57   18.881,38   20.043,82   20.795,56   
ZAF       347.686,61  380.810,62  424.774,28  391.818,95  422.445,73   
ZMB         1.969,18    2.101,19    2.126,86    2.277,21    2.225,87   
ZWE        11.932,42   10.626,97    9.864,23   10.714,97   10.249,27   

Año             2007        2008        2009        2010        2011  
cod_pais                                                              
ABW         2.592,57    2.508,23    2.522,90    2.456,89    2.438,56  
AFG         2.280,87    4.217,05    6.776,62    8.470,77   12.251,45  
AGO        25.151,95   27.172,47   29.361,67   29.743,04   29.710,03  
ALB         4.477,41    4.657,09    4.488,41    4.415,07    4.668,09  
AND          539,049     539,049     517,047     517,047     491,378  
...              ...         ...         ...         ...         ...  
WSM          187,017     190,684     198,018     205,352     234,688  
YEM        21.297,94   22.097,34   23.556,81   25.716,67   22.295,36  
ZAF       440.989,75  469.089,97  477.806,43  454.950,02  477.241,72  
ZMB         1.914,17    2.159,86    2.486,23    2.673,24    3.047,28  
ZWE         9.732,22    7.682,37    8.239,75    9.028,15    9.860,56  

[214 rows x 52 columns]

In [249]:
df4_2.loc['ABW']

Año
1960         NaN
1961         NaN
1962         NaN
1963         NaN
1964         NaN
1965         NaN
1966         NaN
1967         NaN
1968         NaN
1969         NaN
1970         NaN
1971         NaN
1972         NaN
1973         NaN
1974         NaN
1975         NaN
1976         NaN
1977         NaN
1978         NaN
1979         NaN
1980         NaN
1981         NaN
1982         NaN
1983         NaN
1984         NaN
1985         NaN
1986     179,683
1987     447,374
1988     612,389
1989     649,059
1990    1.840,83
1991    1.928,84
1992    1.723,49
1993    1.771,16
1994    1.763,83
1995    1.782,16
1996    1.800,50
1997    1.837,17
1998    1.712,49
1999    1.749,16
2000    2.321,21
2001    2.357,88
2002    2.372,55
2003    2.416,55
2004    2.420,22
2005    2.497,23
2006    2.497,23
2007    2.592,57
2008    2.508,23
2009    2.522,90
2010    2.456,89
2011    2.438,56
Name: ABW, dtype: object

In [ ]:
df.to_csv('salida.csv')